# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create a Config.json
        run: |
            ls
            touch key.json
            echo $GOOGLEKEY > key.json
            cat key.json
            touch config.json
            echo $CONFIG > config.json
            cat config.json
            ls
        shell: bash
        env:
          GOOGLEKEY: ${{secrets.GOOGLE_SERVICE_CONECTION}}
          CONFIG: ${{ secrets.CONFIG_BOT }}
        
      - name: Build, Push and Release a Docker container to Heroku.
        # You may pin to the exact commit or the version.
        # uses: gonuit/heroku-docker-deploy@9ab97585f979857642d66612a2ae4062b3347d53
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          # The email address associated with your Heroku account.
          email: ${{ secrets.HEROKU_EMAIL }}
          # Heroku API key associated with provided user's email.
          heroku_api_key:  ${{ secrets.HEROKU_APIKEY }}
          # Dockerfile directory.
          dockerfile_directory: ./
          process_type: botcalendar
